
import java.awt.Color;
import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Monroy
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    String alf[];
    String alf1[];
    String est[];
    String matrizEst[][];
    boolean determinista;
    
    
    public Ventana() {
        determinista = false;


        initComponents();
        
        
        cadTxt.setEnabled(false);
        btnIni.setVisible(false);
        lblCad.setVisible(false);
        cadTxt.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        alfTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iniTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        estTxt = new javax.swing.JTextField();
        finTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmb1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lblCad = new javax.swing.JLabel();
        cadTxt = new javax.swing.JTextField();
        resLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnIni1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Alfabeto:");

        alfTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        alfTxt.setForeground(new java.awt.Color(0, 102, 255));
        alfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Estado Inicial:");

        iniTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        iniTxt.setForeground(new java.awt.Color(0, 102, 255));
        iniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Estados:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Estado Final: ");

        estTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estTxt.setForeground(new java.awt.Color(0, 102, 255));
        estTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estTxtActionPerformed(evt);
            }
        });

        finTxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        finTxt.setForeground(new java.awt.Color(0, 102, 255));

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        btnIni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIni.setText("Nuevos valores ");
        btnIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Capturar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(estTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(alfTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnIni, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(alfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automata Finito No Determinista", "Automata Finito Determinista" }));
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Elejir tipo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addGap(73, 73, 73)
                .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblCad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCad.setText("Cadena a evaluar:");

        cadTxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadTxt.setForeground(new java.awt.Color(0, 102, 255));
        cadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadTxtActionPerformed(evt);
            }
        });
        cadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cadTxtKeyTyped(evt);
            }
        });

        resLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resLbl.setForeground(new java.awt.Color(0, 102, 255));
        resLbl.setText("  ");
        resLbl.setOpaque(true);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnIni1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIni1.setText("Instrucciones");
        btnIni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIni1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)))
                .addGap(82, 82, 82)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );

        setBounds(0, 0, 765, 671);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (cajasVacias()) {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
        } else {
            if (!esAlf(alfTxt.getText().split(","))) {
                JOptionPane.showMessageDialog(this, "alfabeto invalido");
            } else {
                if (!comaSeguida(estTxt.getText())) {
                    alf = ("Q," + alfTxt.getText()).split(",");

                    est = estTxt.getText().split(",");
                    if (estValido(finTxt.getText()) && estValido(iniTxt.getText()) && estValido(iniTxt.getText()) && iniTxt.getText().indexOf(",") == -1) {
                        alfTxt.setEnabled(false);
                        estTxt.setEnabled(false);
                        iniTxt.setEnabled(false);
                        finTxt.setEnabled(false);
                        cadTxt.setEnabled(true);
                        cadTxt.setEnabled(true);
                        btnIni.setVisible(true);
                        lblCad.setVisible(true);
                        cadTxt.setVisible(true);



                        String matrizTabla[][] = new String[est.length][alf.length];
                        for (int i = 0; i < est.length; i++) {
                            matrizTabla[i][0] = est[i];

                        }
                        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                matrizTabla,
                                alf));
                    } else {
                        JOptionPane.showMessageDialog(this, "No concuerdan los estados");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Estados mal escritos");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadTxtActionPerformed

        if (determinista) {
            if (jTableValidoAFD()) {
                if (analizador()) {
                    resLbl.setText("   Cadena valida");
                    resLbl.setBackground(Color.white);
                } else {
                    resLbl.setText("   Cadena no valida");
                    resLbl.setBackground(Color.red);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hay errores en la tabla de estados");
            }
        } else {
            if (jTableValidoAFN()) {
                if (analizador()) {
                    resLbl.setText("   Cadena válida");
                    resLbl.setBackground(Color.white);
                } else {
                    resLbl.setText("   Cadena no válida");
                    resLbl.setBackground(Color.red);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hay errores en la tabla de estados");
            }
        }
    }//GEN-LAST:event_cadTxtActionPerformed

    private void estTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estTxtActionPerformed

    private void alfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfTxtActionPerformed

    private void cadTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadTxtKeyTyped
        if (!estaEnAlf("" + evt.getKeyChar())) {
            evt.consume();
        } else {
            resLbl.setBackground(new Color(240, 240, 240));
            resLbl.setText(" ");
        }
    }//GEN-LAST:event_cadTxtKeyTyped

    private void btnIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniActionPerformed
        String ar[] = {"Si", "No"};
        int opcion = JOptionPane.showOptionDialog(this, "Se borraran los valores en la tabla de transicion\n ¿Desea continuar?",
                "Advertencia",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, //do not use a custom Icon
                ar, //the titles of buttons
                ar[1]); //default button title

        if (opcion == 0) {
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{}, new String[]{}));
            alfTxt.setEnabled(true);
            estTxt.setEnabled(true);
            iniTxt.setEnabled(true);
            finTxt.setEnabled(true);

            cadTxt.setText("");

            cadTxt.setVisible(false);
            btnIni.setVisible(false);
            lblCad.setVisible(false);
            cadTxt.setVisible(false);
            resLbl.setBackground(new Color(240, 240, 240));
            resLbl.setText("");
        }

    }//GEN-LAST:event_btnIniActionPerformed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void iniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
          if(cmb1.getSelectedIndex()==0){
            determinista = false;
          }
          if(cmb1.getSelectedIndex()==1){
            determinista = true;
          }
    }//GEN-LAST:event_cmb1ActionPerformed

    private void btnIni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIni1ActionPerformed
          AcercaDe a=new AcercaDe();
          a.setVisible(true);
    }//GEN-LAST:event_btnIni1ActionPerformed
    public boolean cajasVacias() {
        return (estTxt.getText().equals("") || estTxt.getText().equals("") || estTxt.getText().equals("") || iniTxt.getText().equals("") || finTxt.getText().equals(""));




    }

    public boolean comaSeguida(String cad) {

        int cont = 0;
        if (cad.charAt(0) == ',') {
            return true;
        }
        if (cad.charAt(cad.length() - 1) == ',') {
            return true;
        }
        for (int i = 0; i < cad.length(); i++) {
            if (cad.charAt(i) == ',') {
                cont++;
            } else {
                cont = 0;
            }

            if (cont > 1) {
                return true;
            }


        }
        return false;
    }

    public boolean esAlf(String[] v) {
        for (int i = 0; i < v.length; i++) {
            if (v[i].length() != 1) {
                return false;
            }
        }
        if (comaSeguida(alfTxt.getText())) {
            return false;
        }

        return true;
    }

    public boolean estaEnAlf(String cad) {
        for (int i = 0; i < alf.length; i++) {
            if (cad.compareTo(alf[i]) == 0) {
                return true;
            }
        }
        return false;
    }

    public boolean estaEnEst(String cad) {
        for (int i = 0; i < est.length; i++) {
            if (cad.compareTo(est[i]) == 0) {
                return true;
            }
        }
        return false;
    }

    public int getIndiceAlf(String cad) {
        for (int i = 0; i < alf.length; i++) {
            if (cad.compareTo(alf[i]) == 0) {
                return i;
            }
        }
        return -1;
    }

    public int getFilaMatriz(String cad) {
        for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {
            if (cad.compareTo(jTable1.getModel().getValueAt(i, 0).toString()) == 0) {
                return i;
            }
        }
        return -1;
    }

    public boolean jTableValidoAFN() {

        for (int j = 0; j < jTable1.getRowCount(); j++) {
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                //            JOptionPane.showMessageDialog(this, jTable1.getModel().getValueAt(j, i).toString() + "putos todos");
                if (jTable1.getModel().getValueAt(j, i) == null) {
                    return false;
                } else {

                    if (jTable1.getModel().getValueAt(j, i).toString().compareTo("") == 0) {
                        return false;
                    } else {
                        if (jTable1.getModel().getValueAt(j, i).toString().compareTo("-") == 0) {
                            return true;
                        } else {

                            if (comaSeguida(jTable1.getModel().getValueAt(j, i).toString())) {
                                return false;
                            } else {
                                String ar[] = jTable1.getModel().getValueAt(j, i).toString().split(",");
                                for (int k = 0; k < ar.length; k++) {
                                    if (!estaEnEst(ar[k])) {
                                        return false;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return true;
    }

    public boolean jTableValidoAFD() {

        for (int j = 0; j < jTable1.getRowCount(); j++) {
            for (int i = 0; i < jTable1.getColumnCount(); i++) {

                if (jTable1.getModel().getValueAt(j, i) == null) {
                    return false;
                } else {

                    if (jTable1.getModel().getValueAt(j, i).toString().compareTo("") == 0) {
                        return false;
                    } else {
                        if (jTable1.getModel().getValueAt(j, i).toString().compareTo("-") == 0) {
                            return false;
                        } else {

                            if (comaSeguida(jTable1.getModel().getValueAt(j, i).toString())) {
                                return false;
                            } else {
                                if (!estaEnEst(jTable1.getModel().getValueAt(j, i).toString())) {
                                    return false;
                                }
                            }
                        }
                    }
                }
            }
        }
        return true;
    }

    boolean esFin(String est) {
        String arr[] = finTxt.getText().split(",");
        for (int i = 0; i < arr.length; i++) {
            if (arr[i].compareTo(est) == 0) {
                return true;
            }
        }

        return false;
    }

    boolean analizador() {
        String estActual = iniTxt.getText();
        ArrayList cadena[] = new ArrayList[cadTxt.getText().length()];
        int i = 0;
        boolean entrar = true;
        do {
            System.out.println("En la letra "+i);
            if (i ==  cadena.length) {
                //checar final
                if(esFin(estActual))
                {
                  entrar=false;
                }
                else
                {
                  i--;
                  
                }
            } 
            else 
            {
                if (cadena[i] == null) 
                {
                    int columna = getIndiceAlf("" + cadTxt.getText().charAt(i));
                    int fila = getFilaMatriz(estActual);
                    System.out.println("i: "+i+"fila: "+fila+" col: "+columna);
                    if (columna == -1 || fila == -1) {
                        i--;
                        
                    } 
                    else 
                    {
                        String tmp[] = jTable1.getValueAt(fila, columna).toString().split(",");
                        cadena[i]=new ArrayList();
                        for (int j = 0; j < tmp.length; j++) {
                            cadena[i].add(tmp[j]);
                        }
                        estActual=cadena[i].get(0).toString();
                        i++;
                    }
                }
                else
                {
                  //verificar si esta vacio el arrayList
                    System.out.println("i: "+i+" size: "+cadena[i].size());
                    if(cadena[i].size()==1)
                    {
                        cadena[i]=null;
                        i--;
                    }
                    else
                    {
                      cadena[i].remove(0);
                      estActual=cadena[i].get(0).toString();
                      i++;
                    }
                }                
            }
        } while (i > -1 && entrar);
        if(entrar)
            return false;
        else
            return true;
    }

    boolean estValido(String cad) {
        String ar[] = cad.split(",");
        for (int i = 0; i < ar.length; i++) {
            if (!estaEnEst(ar[i])) {
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alfTxt;
    private javax.swing.JButton btnIni;
    private javax.swing.JButton btnIni1;
    private javax.swing.JTextField cadTxt;
    private javax.swing.JComboBox cmb1;
    private javax.swing.JTextField estTxt;
    private javax.swing.JTextField finTxt;
    private javax.swing.JTextField iniTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCad;
    private javax.swing.JLabel resLbl;
    // End of variables declaration//GEN-END:variables
}
